# Generated by Django 5.2.6 on 2025-09-18 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del paciente', max_length=100)),
                ('fecha', models.DateField(help_text='Fecha de la cita')),
                ('hora', models.TimeField(help_text='Hora de la cita')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción de la cita')),
                ('creada_en_ghl', models.BooleanField(default=False, help_text='¿La cita fue reflejada en GHL?')),
            ],
        ),
    ]
